site_name: dx-Dash
site_url: https://awadih.github.io/dx-Dash/
site_author: A. Wadih
site_description: "dx-Dash App documentation & further features"
repo_url: "https://github.com/awadih/dx-Dash"
copyright: "dx-Dash is licensed under the <a href='https://github.com/awadih/dx-Dash/blob/main/LICENSE.md'>MIT license</a>"
theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: github
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  favicon: img/favicon.ico
nav:
  - 'Home':
    - 'Overview': 'index.md'
    - 'Current location': 'research/1.current_location.md'
    - 'Current weather': 'research/2.current_weather_data.md'
    - 'Alerts': 'research/3.alerts.md'
    - 'API limitation': 'research/4.api_limitations.md'
  - 'Prototyping & Design':
      - 'Wireframe': 'prototyping/1.tools.md'
      - 'UI': 'design/user_interface.md'
  - 'Development':
      - 'Dev-Framework': 'development/dev_framework.md'
      - 'Tasks': 'todos.md'
  - 'Testing & Deployment':
      - 'Testing-Framework': 'testing/test_framework.md'
      - 'Hosting platform': 'deployment/hosting_platform.md'
  - 'License': 'license.md'